# Generated by Django 4.0.4 on 2022-06-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmeti',
            name='nositelj_predmet',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predmeti', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
