# Generated by Django 4.0.4 on 2022-06-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_predmeti_nositelj_predmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='izborni',
            field=models.CharField(blank=True, choices=[('DA', 'da'), ('NE', 'ne')], max_length=50),
        ),
        migrations.CreateModel(
            name='Pomocna_tablica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kod', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('ects', models.IntegerField()),
                ('sem_red', models.IntegerField()),
                ('sem_izv', models.IntegerField()),
                ('izborni', models.CharField(blank=True, choices=[('DA', 'da'), ('NE', 'ne')], max_length=50)),
                ('nositelj_predmet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomocna', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
