# Generated by Django 4.0.4 on 2022-06-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_predmeti_izborni_pomocna_tablica'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pomocna_tablica',
            new_name='Pomocna_tablica_neupisani_izv',
        ),
    ]
