# Generated by Django 4.0.4 on 2022-06-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_pomocna_tablica_pomocna_tablica_neupisani_izv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='ects',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='izborni',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='kod',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='nositelj_predmet',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='program',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='sem_izv',
        ),
        migrations.RemoveField(
            model_name='pomocna_tablica_neupisani_izv',
            name='sem_red',
        ),
        migrations.AddField(
            model_name='pomocna_tablica_neupisani_izv',
            name='predmet_neupisani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomocna_tablica', to='App.predmeti'),
        ),
    ]
