# Generated by Django 4.0.4 on 2022-06-19 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_pomocna_tablica_neupisani_izv_user_neupisani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomocna_tablica_neupisani_izv',
            name='predmet_neupisani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomocna_tablica_izv', to='App.predmeti'),
        ),
        migrations.AlterField(
            model_name='pomocna_tablica_neupisani_izv',
            name='user_neupisani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomocna_tablica_izv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pomocna_tablica_neupisani_red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet_neupisani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomocna_tablica_red', to='App.predmeti')),
                ('user_neupisani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomocna_tablica_red', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
