# Generated by Django 4.0.4 on 2022-06-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_pomocna_tablica_neupisani_izv_predmet_neupisani_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomocna_tablica_neupisani_red',
            old_name='predmet_neupisani',
            new_name='predmet_neupisani_red',
        ),
        migrations.RenameField(
            model_name='pomocna_tablica_neupisani_red',
            old_name='user_neupisani',
            new_name='user_neupisani_red',
        ),
    ]
